# Generated by Django 5.0.2 on 2024-05-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='embedded',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
